### PR TITLE
Checks for upstream cleanup

### PR DESCRIPTION
**Pull request by jaimergp**
Opening this PR just to run the upstream tests with the cleaned branch. We will start with tons of failures (don't panic) but we will end up in all-green land once we are done!

### CODE REVIEW

**Comment by jaimergp** [comment]
These tests are failing now without modifications upstream:

```
tests/conda_env/test_cli.py::IntegrationTests::test_create_dry_run_yaml
tests/core/test_solve.py::test_channel_priority_churn_minimized
tests/core/test_solve.py::test_conda_downgrade
tests/core/test_solve.py::test_cuda_fail_1
tests/core/test_solve.py::test_cuda_fail_2
tests/core/test_solve.py::test_downgrade_python_prevented_with_sane_message
tests/core/test_solve.py::test_fast_update_with_update_modifier_not_set
tests/core/test_solve.py::test_force_remove_1
tests/core/test_solve.py::test_freeze_deps_1
tests/core/test_solve.py::test_freeze_deps_1
tests/core/test_solve.py::test_only_deps_1
tests/core/test_solve.py::test_pinned_1
tests/core/test_solve.py::test_pinned_1
tests/core/test_solve.py::test_priority_1
tests/core/test_solve.py::test_python2_update
tests/core/test_solve.py::test_update_all_1
tests/test_create.py::IntegrationTests::test_neutering_of_historic_specs
tests/test_create.py::IntegrationTests::test_offline_with_empty_index_cache
tests/test_create.py::IntegrationTests::test_pinned_override_with_explicit_spec
```

Our previous solution to these failures involved adjusting the expectations of the test to reflect the spirit of the check itself, and not the strict solution upstream is testing for. However, doing that now would involve adding plugin-specific details upstream, among other details that would couple `conda/conda` a bit too much with this work.

Alternatively, we can skip the upstream counterparts and copy those tests to our repo here, adjusting the checks accordingly. The downside here is that we would need to keep our copies up-to-date if upstream changes.

Thoughts @jezdez?

**Comment by jezdez** [comment]
@jaimergp Let's copy them over to make sure we tests this library how we're intended to test it and leave a comment where there were copied from, to update them if needed. I don't think we'll see a lot of updates upstream anyways.

**Comment by jaimergp** [comment]
Ok! Ready for review then @jezdez 

I added the test skip list to our own `pyproject.toml` file, which we then use to override `conda/conda`'s pytest configuration. I tried to find an environment variable akin to `pytest -c config_file` but there's none afaik... so dirty it is :D

**Comment by jezdez** [comment]
> Ok! Ready for review then @jezdez
> 
> I added the test skip list to our own `pyproject.toml` file, which we then use to override `conda/conda`'s pytest configuration. I tried to find an environment variable akin to `pytest -c config_file` but there's none afaik... so dirty it is :D

I *think* you can [use `pytest --rootdir=/path/with/pyproject.toml` for this](https://docs.pytest.org/en/6.2.x/customize.html#initialization-determining-rootdir-and-configfile), but I'm not sure.

**Comment by jaimergp** [comment]
> I think you can [use pytest --rootdir=/path/with/pyproject.toml for this](https://docs.pytest.org/en/6.2.x/customize.html#initialization-determining-rootdir-and-configfile), but I'm not sure.

The problem is more about not being able to edit the pytest calls happening in `conda/conda` testing scripts. If we could set the env var and export it maybe that'd work, but regardless the CLI flag, we are left we overwriting configurations for now :(

**Review by jezdez — APPROVED** [review]
This is ready! 👍🏻

**Comment by jaimergp** [comment]
No clue what's wrong with Windows but I am not waiting any longer :D If it's a problem on the push to main we'll fix with another PR.

**Comment by jaimergp** [comment]
Oh, it can be rebuilt even after closing. Nice!

**Pull request merged**
